### ISSUE TITLE
“遭”字粗字重渲染错误

### ISSUE THREAD

**Issue by LoveCatc** [lxgw/LxgwZhenKai#2]
![Screenshot_2022-02-13-10-47-00-951_com zhihu android](https://user-images.githubusercontent.com/48412571/153736106-d6bf89f9-6d8a-4c79-b603-a3fc56cb14ea.jpg)
如图，在知乎粗字体标题中“遭”字似乎出现了错误的渲染。
手机系统版本：mix4 miui12.5.12稳定版
magisk版本：23015
字体版本：霞鹜臻楷 v0.5 22/01/29

**Comment by lxgw** [comment]
下个版本将会解决。

**Comment by LoveCatc** [comment]
[自动回复]您好，我已收到您的邮件。感谢您的来信。

**Comment by LoveCatc** [comment]
[自动回复]您好，我已收到您的邮件。感谢您的来信。
