### ISSUE TITLE
还是看不清...

### ISSUE THREAD

**Issue by BetterWorld-Liuser** [lxgw/LxgwZhenKai#4]
原对比图，
![image](https://user-images.githubusercontent.com/37199800/159111765-b107ccf0-a5b0-4f3b-be5f-fc6d8c1d348c.png)
再加粗，就能看清了
![image](https://user-images.githubusercontent.com/37199800/159111777-94dd1eff-1552-49d9-b5e6-8b47777c4936.png)

**Comment by lxgw** [comment]
非常抱歉，让您不满意了。

**Comment by BetterWorld-Liuser** [comment]
我不是那个意思呀，我的意思是对比起来有这个问题，所以提了issue，呜呜呜。刚才也查了font creator应该怎么加粗...还是挺麻烦的，非常感谢你提供的字体。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lxgw/LxgwZhenKai] 还是看不清... (Issue #4)




 
非常抱歉，让您不满意了。

**Comment by lxgw** [comment]
> 我不是那个意思呀，我的意思是对比起来有这个问题，所以提了issue，呜呜呜。刚才也查了font creator应该怎么加粗...还是挺麻烦的，非常感谢你提供的字体。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年3月19日(周六) 下午3:32 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [lxgw/LxgwZhenKai] 还是看不清... (Issue #4) 非常抱歉，让您不满意了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

刚才我把我的评论编辑了一下。

> 非常抱歉，目前粗度的选择上还是有些保守了，不过既然选择了这个粗度，就只能一直做下去，再加粗的话还需要细调甚至需要重做，望您理解。

**Comment by BetterWorld-Liuser** [comment]
好的，谢谢您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午4:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lxgw/LxgwZhenKai] 还是看不清... (Issue #4)




  
我不是那个意思呀，我的意思是对比起来有这个问题，所以提了issue，呜呜呜。刚才也查了font creator应该怎么加粗...还是挺麻烦的，非常感谢你提供的字体。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年3月19日(周六) 下午3:32 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [lxgw/LxgwZhenKai] 还是看不清... (Issue #4) 非常抱歉，让您不满意了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
刚才我把我的评论编辑了一下。
  
非常抱歉，目前粗度的选择上还是有些保守了，不过既然选择了这个粗度，就只能一直做下去，再加粗的话还需要细调甚至需要重做，望您理解。
