### ISSUE TITLE
本字体在字重的选择上，是否过于保守？

### ISSUE THREAD

**Issue by lxgw** [lxgw/LxgwZhenKai#6]
如题，当初加粗的时候，选择加粗 10 个单位，再粗怕糊成一片而且不好调整，结果还是有人觉得细……

![e46ad6ed4a1244060448a8c0e001df2b.png](https://user-images.githubusercontent.com/51902309/163589285-f736e3f5-ce6c-47db-9209-e1f02898ab37.png)

![0e45a40d98f41a3af5c3b04342857019.png](https://user-images.githubusercontent.com/51902309/163589302-bf062008-6a4b-4993-8c19-d9a09574a832.png)

本字体在字重的选择上，是否过于保守？如果是，可能需要重新制作，因为笔画需要细调，需要更多的时间。

也有可能，这款字体可能会面临调整。

**Comment by chengnan049** [comment]
无必要

**Comment by lxgw** [comment]
![I2GB`M02WW$96HXH4IZMDA4](https://user-images.githubusercontent.com/51902309/171518193-bd331226-b553-4b30-b5ac-7c0e4667305e.png)

**Comment by nanvon** [comment]
我觉得还是维持目前臻楷的粗度较好，作为文楷的粗体版本，目前的臻楷已经非常成熟、字数覆盖已经很全了（尽管后面是机械加粗的）。字体类别的产品，难以统计调查大部分用户对粗度的想法，作者您或许需要判断是否是**大多数**用户觉得粗度还不够。

**Comment by CoelacanthusHex** [comment]
如果作为比文楷的 Bold 字重更重的字重（也就是当作屏幕阅读的粗体），那确实偏细，对比不够
如果是作为单独使用的字体，刚刚好

**Comment by CoelacanthusHex** [comment]
所以要不要继续加粗，还是要看这个字体的设计目的（不过我个人的意见是，无论是不是要在臻楷上做，我希望有一个足够粗度的字体，作为屏幕阅读版本文楷的粗体，有些程序是不会自己生成伪粗体的）

**Comment by CoelacanthusHex** [comment]
如果你做臻楷目的是单独的字体的话，感觉你可以和说到底同学合作，你继续维护这个粗度的臻楷，他维护一个用作屏幕阅读的粗体版本，然后你们互通消息，比如哪个字容易发生粘连需要处理
当然，这仅仅是我个人的建议

**Comment by Ventulus-lab** [comment]
确实，主要是文楷常规太细了，如果文楷常规是常用字体，那臻楷作为bold加粗是合适的；但现在文楷med作为常用字体才看得舒服，臻楷作为bold差别就太小了，恐怕得上heavy才能有粗体的感觉。
