### ISSUE TITLE
希望可以添加“祂”字

### ISSUE THREAD

**Issue by edophantom** [lxgw/LxgwZhenKai#7]
作为一个游戏文案，“祂”算是一个相当常用的字用以称呼神明，希望可以采纳这一意见。

**Comment by lxgw** [comment]
[用文楷吧（](https://www.coolapk.com/feed/36502442?shareKey=NDhhODA0NDY5NDAwNjI5ZTk3YzM~&shareUid=633884&shareFrom=com.coolapk.market_12.3)

**Comment by edophantom** [comment]
> [用文楷吧，本字体不打算再更新了（](https://www.coolapk.com/feed/36502442?shareKey=NDhhODA0NDY5NDAwNjI5ZTk3YzM~&shareUid=633884&shareFrom=com.coolapk.market_12.3)

az

**Comment by edophantom** [comment]
> [用文楷吧，本字体不打算再更新了（](https://www.coolapk.com/feed/36502442?shareKey=NDhhODA0NDY5NDAwNjI5ZTk3YzM~&shareUid=633884&shareFrom=com.coolapk.market_12.3)

总之还是感谢创作者的辛勤付出~比心
