### ISSUE TITLE
更新下小米里的字体呗😂

### ISSUE THREAD

**Issue by swjtu-cell** [lxgw/LxgwZhenKai#8]

**Comment by lxgw** [comment]
小米主题商店里由他人代上传的《霞鹜臻楷》早已下架；此外本人没有小米主题设计师账号，也没有达到小米主题平台注册字体设计师的条件（3 份原创作品版权登记证明），因此无法满足您的需求。建议您选用主题商店里类似的版权字体。

**Comment by swjtu-cell** [comment]
好吧
